### ISSUE TITLE
Support for log4j2

### ISSUE THREAD

**Issue by brianhks** [miguno/puppet-storm#11]
The latest storm moved from logback to log4j2, any plans to accommodate that?

**Comment by miguno** [comment]
I'm happy to review any PRs that add log4j2 support.  At the moment I don't have the bandwidth to work on it myself.

**Comment by brianhks** [comment]
Well to your credit I didn't have to do anything to your module in order to support log4j2.  I just changed the log file and template to a log4j2 configuration file like so:
`class { 'storm':
    logback => '/opt/storm/log4j2/cluster.xml',
    logback_template => 'profile_storm/cluster.xml.erb',
    logback_worker => '/opt/storm/log4j2/worker.xml',
    logback_worker_template => 'profile_storm/worker.xml.erb'

  }`

**Comment by miguno** [comment]
Great, happy to hear you could make it work without a lot of hassle!
