### ISSUE TITLE
Add metadata.json for librarian-puppet

### ISSUE THREAD

**Issue by davidsnyder** [miguno/puppet-storm#4]
We're using librarian-puppet to manage our modules and when installing puppet-storm the `puppet module list` output shows no version:

    ├── storm (???)

which is due to there being no `metadata.json` for puppet to parse.  When using `puppet module build` to install modules, puppet will generate a `metadata.json` for you from the deprecated `Modulefile`, but when using librarian-puppet to manage modules this doesn't happen.

It's a minor inconvenience, but it would be great if your puppet-* modules included a `metadata.json`!

**Comment by miguno** [comment]
Closing this for now because of inactivity.  Feel free to reopen if you think otherwise!
