### ISSUE TITLE
using ENC instead of hiera

### ISSUE THREAD

**Issue by karmab** [miguno/puppet-storm#5]
hello, i m using foreman to deploy your brillant puppet classes but saw customizing things like 
`storm::nimbus_host` or `storm::zookeeper_servers` or `storm::drpc_servers` was only possible using hiera, since you re inheriting storm base class and not instantiating it on the child classes.
any idea how to overcome that?

**Comment by miguno** [comment]
I am closing this for now because there hasn't been progress since October last year.  Feel free to reopen if you think otherwise!
